import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar";
import Providers from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",  // Define the variable for Geist font
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",  // Define the variable for Geist Mono font
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",  // Define the variable for Inter font
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quizly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${inter.variable}`,  // Reference to the Inter font variable
          `${geistSans.variable}`,  // Reference to the Geist font variable
          'antialiased min-h-screen pt-16'
        )}
      >
        <Providers>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Toaster />
          </ThemeProvider>
          </Providers>
      </body>
    </html>
  );
}
